### ISSUE TITLE
部署相关咨询

### ISSUE THREAD

**Issue by DDAccount** [blacktunes/hiiro-button#15]
感谢模板和工具。
我在用命令行工具生成模板，按照指引替换/修改相应内容，可以成功部署到了github page。
但当我想更新增加新的语音时，出现了这样的问题：
在本地yarn serve调试一切正常；
yarn build后dist的可部署文件推送到部署的仓库，打开github page，分类（category）查看可以看到有按钮更新，但按出处查看，属于新增的title的一整块都没有出现。
这个问题应该怎么解决？

**Comment by blacktunes** [comment]
我下午更新模板的时候顺便看一下

**Comment by DDAccount** [comment]
> 我下午更新模板的时候顺便看一下

解决了，应该是我在语音文件的json里，name或者zh-CN填了“！@#￥%……&”这段，或者en-US填了“!@#$%^&”这段，换成常规字符就ok了。
至于为什么我本地解析没问题，github page部署有问题，就不知道了。
