### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by LightQuanta** [blacktunes/hiiro-button#6]
我是域名<https://hiifan.icu/>的持有者
我感觉你现在这个域名比较一般，别人可能不太一样记得住
我这个hiifan.icu就很生草，保证其他人看一下就可以记住并且永远都忘不掉（
而且我这官网也几个月没更新过了，给我自己留着的话也没啥用（
所以你要不要考虑使用我这个域名，我可以把<https://hiifan.icu>解析到你这
除此之外，我和hiiro是QQ好友，如果你想推荐你的网站我可以直接私信跟她说，我相信我推荐后她有很高的概率会在直播里看你这个网站的
你要不要考虑一下？

**Comment by KarewaGron** [comment]
19岁，是学生

**Comment by ous50** [comment]
![image](https://user-images.githubusercontent.com/36183551/100250083-2ecea980-2f35-11eb-9b12-1b8a78d8ee52.png)

**Comment by blacktunes** [comment]
我考虑一下吧，因为这个域名已经传播出去，现在再去改域名其实并不太好。

hiiro是知道这个网站的，建站和上传语音我都问过她的意见，是否打算在直播里出现还是看她自己决定好了

**Comment by ous50** [comment]
个人觉得其实可以同步上线，~~让DD们有更多生草方案~~

**Comment by LightQuanta** [comment]
> 是否打算在直播里出现还是看她自己决定好了

其实我感觉也不一定要改，可以两个域名一起用啊
可以让<https://hiifan.icu/>和<https://hiiro.club/>都指向这个网页
至于直播倒是无所谓，不过我感觉用我这个域名能让网站更容易被记住

**Comment by blacktunes** [comment]
> 其实我感觉也不一定要改，可以两个域名一起用啊
> 可以让https://hiifan.icu/和https://hiiro.club/都指向这个网页
> 至于直播倒是无所谓，不过我感觉用我这个域名有助于网站更容易被记住

一起用倒是没什么问题，看你自己决定咯，要解析过来的话就做个CNAME或者301，不解析的话加个友链也一样
