### ISSUE TITLE
我可以添加m4r格式的版本吗

### ISSUE THREAD

**Issue by ous50** [blacktunes/hiiro-button#9]

**Comment by ous50** [comment]
我自己会下载这些音频到本地并转制为m4r格式，导入iOS设备用
想传一份到你的project里，给iOS用家提供一个选择如何？

**Comment by blacktunes** [comment]
抱歉，一不小心忘了回复了
你可以新建一个仓库用于存放`m4r`文件，我在`README.md`写上该仓库的`url`
